export const AUDIT_EVENT_TYPES = [
  'event.created',
  'event.updated',
  'event.archived',
  'event.unarchived',
  'event.started',
  'event.stopped',
  'event.featured',
  'event.unfeatured',
  'event.duplicated',
  'event_game.added',
  'event_game.removed',
  'event_game.enabled',
  'event_game.disabled',
  'event_game.updated',
  'event_game.reordered',
  'objective.created',
  'objective.updated',
  'objective.deleted',
  'objective.predefined_created',
  'objective.predefined_assigned',
  'objective.predefined_imported',
  'objective.reordered',
  'objective.completed',
  'objective.uncompleted',
  'objective.completion_time_edited',
  'objective.failed',
  'objective.unfailed',
  'objective.remaining_failed',
  'competitor.added',
  'competitor.removed',
  'streamer.live_changed',
  'streamer.added',
  'streamer.removed',
  'moderator.added',
  'moderator.removed',
  'competitor_info.added',
  'competitor_info.updated',
  'competitor_info.removed',
  'overlay_token.created',
  'overlay_token.revoked',
  'overlay_token.settings_updated',
  'twitch_extension.configuration_updated',
  'twitch_extension.settings_updated',
  'user.role_changed',
  'allowlist.added',
  'allowlist.removed',
  'feature_flag.updated',
  'media.uploaded',
  'trial_run.enabled',
  'trial_run.disabled',
  'trial_run.started',
  'trial_run.stopped',
  'trial_run.reset',
] as const

export type AuditEventType = (typeof AUDIT_EVENT_TYPES)[number]

export const AUDIT_EVENT_TYPE_LABELS: Record<AuditEventType, string> = {
  'event.created': 'Event created',
  'event.updated': 'Event updated',
  'event.archived': 'Event archived',
  'event.unarchived': 'Event unarchived',
  'event.started': 'Event started',
  'event.stopped': 'Event stopped',
  'event.featured': 'Event featured',
  'event.unfeatured': 'Event unfeatured',
  'event.duplicated': 'Event duplicated',
  'event_game.added': 'Game added',
  'event_game.removed': 'Game removed',
  'event_game.enabled': 'Game enabled',
  'event_game.disabled': 'Game disabled',
  'event_game.updated': 'Game updated',
  'event_game.reordered': 'Games reordered',
  'objective.created': 'Objective created',
  'objective.updated': 'Objective updated',
  'objective.deleted': 'Objective deleted',
  'objective.predefined_created': 'Predefined objective created',
  'objective.predefined_assigned': 'Predefined objective assigned',
  'objective.predefined_imported': 'Predefined objectives imported',
  'objective.reordered': 'Objectives reordered',
  'objective.completed': 'Objective completed',
  'objective.uncompleted': 'Objective uncompleted',
  'objective.completion_time_edited': 'Completion time edited',
  'objective.failed': 'Objective failed',
  'objective.unfailed': 'Objective failure cleared',
  'objective.remaining_failed': 'Remaining objectives failed',
  'competitor.added': 'Competitor added',
  'competitor.removed': 'Competitor removed',
  'streamer.live_changed': 'Streamer live status changed',
  'streamer.added': 'Streamer added',
  'streamer.removed': 'Streamer removed',
  'moderator.added': 'Moderator added',
  'moderator.removed': 'Moderator removed',
  'competitor_info.added': 'Competitor info added',
  'competitor_info.updated': 'Competitor info updated',
  'competitor_info.removed': 'Competitor info removed',
  'overlay_token.created': 'Overlay token created',
  'overlay_token.revoked': 'Overlay token revoked',
  'overlay_token.settings_updated': 'Overlay token look updated',
  'twitch_extension.configuration_updated': 'Twitch extension channel settings updated',
  'twitch_extension.settings_updated': 'Twitch extension rules updated',
  'user.role_changed': 'User role changed',
  'allowlist.added': 'Allowlist entry added',
  'allowlist.removed': 'Allowlist entry removed',
  'feature_flag.updated': 'Feature flag updated',
  'media.uploaded': 'Media uploaded',
  'trial_run.enabled': 'Trial run enabled',
  'trial_run.disabled': 'Trial run disabled',
  'trial_run.started': 'Trial run started',
  'trial_run.stopped': 'Trial run stopped',
  'trial_run.reset': 'Trial run reset',
}

export const getAuditTypeLabel = (type: string) =>
  type in AUDIT_EVENT_TYPE_LABELS ? AUDIT_EVENT_TYPE_LABELS[type as AuditEventType] : type
