// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Soulsjwa.Api.Infrastructure.Data;

#nullable disable

namespace Soulsjwa.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913011520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Soulsjwa.Api.Features.Admin.Entities.FeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("Key");

                    b.ToTable("FeatureFlags");

                    b.HasData(
                        new
                        {
                            Key = "myevents.quick_complete.enabled",
                            Enabled = false
                        });
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Audits.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EventGameId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("SubjectUserId");

                    b.HasIndex("Type");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("EventId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_AuditLogs_EventId_CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.AllowlistedTwitchLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TwitchLogin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("TwitchLogin")
                        .IsUnique();

                    b.ToTable("AllowlistedTwitchLogins");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAllowlisted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Calendar.Entities.CalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionMarkdown")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ImageAssetId");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("IX_CalendarEntries_StartsAt");

                    b.HasIndex("EventId", "StartsAt");

                    b.ToTable("CalendarEntries");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Calendar.Entities.PlannedRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventGameId");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("IX_PlannedRuns_StartsAt");

                    b.HasIndex("EventId", "StartsAt");

                    b.HasIndex("UserId", "StartsAt");

                    b.ToTable("PlannedRuns");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.CompletedObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("InGameTimeMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrialRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrialRunId");

                    b.HasIndex("UserId");

                    b.HasIndex("ObjectiveId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CompletedObjectives_ObjectiveId_UserId_Official")
                        .HasFilter("\"TrialRunId\" IS NULL");

                    b.HasIndex("ObjectiveId", "UserId", "TrialRunId")
                        .IsUnique()
                        .HasDatabaseName("IX_CompletedObjectives_ObjectiveId_UserId_TrialRunId")
                        .HasFilter("\"TrialRunId\" IS NOT NULL");

                    b.ToTable("CompletedObjectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowTrialRuns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TieBreakMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlAlias")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Events_CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_Events_Description_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("IsFeatured")
                        .IsUnique()
                        .HasDatabaseName("IX_Events_FeaturedEvent")
                        .HasFilter("\"IsFeatured\"");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Events_Name_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UrlAlias")
                        .IsUnique();

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Events_UrlAlias_Lowercase", "\"UrlAlias\" IS NULL OR \"UrlAlias\" = lower(\"UrlAlias\")");
                        });
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventCompetitor", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStreamer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "IsStreamer");

                    b.ToTable("EventCompetitors");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventCompetitorModerator", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "CompetitorUserId", "ModeratorUserId");

                    b.HasIndex("ModeratorUserId");

                    b.HasIndex("EventId", "ModeratorUserId");

                    b.ToTable("EventCompetitorModerators");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomGameDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CustomGameName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("KnownGameId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventGames_EventId_ActiveGame")
                        .HasFilter("\"IsEnabled\"");

                    b.HasIndex("KnownGameId");

                    b.HasIndex("EventId", "KnownGameId")
                        .HasFilter("\"KnownGameId\" IS NOT NULL");

                    b.ToTable("EventGames");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventGameCompetitorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UserId");

                    b.HasIndex("EventGameId", "UserId");

                    b.ToTable("EventGameCompetitorInfos");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventOverlayToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EventId", "TokenPrefix");

                    b.ToTable("EventOverlayTokens");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventRules", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EventId");

                    b.ToTable("EventRules");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.FailedObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("InGameTimeMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrialRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrialRunId");

                    b.HasIndex("UserId");

                    b.HasIndex("ObjectiveId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_FailedObjectives_ObjectiveId_UserId_Official")
                        .HasFilter("\"TrialRunId\" IS NULL");

                    b.HasIndex("ObjectiveId", "UserId", "TrialRunId")
                        .IsUnique()
                        .HasDatabaseName("IX_FailedObjectives_ObjectiveId_UserId_TrialRunId")
                        .HasFilter("\"TrialRunId\" IS NOT NULL");

                    b.ToTable("FailedObjectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EventGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailRule")
                        .HasColumnType("jsonb");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rule")
                        .HasColumnType("jsonb");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventGameId");

                    b.HasIndex("GameId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.TrialRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventGameId", "UserId")
                        .IsUnique();

                    b.ToTable("TrialRuns");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Games.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConnectorSupported")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequiredConnectorVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectorSupported = true,
                            Description = "Action RPG known for its challenging gameplay and interconnected world design.",
                            Name = "Dark Souls: Remastered",
                            RequiredConnectorVersion = "3.2.0"
                        },
                        new
                        {
                            Id = 2,
                            ConnectorSupported = true,
                            Description = "Sequel featuring a new world with expanded multiplayer and build variety.",
                            Name = "Dark Souls II: Scholar of the First Sin",
                            RequiredConnectorVersion = "3.2.0"
                        },
                        new
                        {
                            Id = 3,
                            ConnectorSupported = true,
                            Description = "The final entry in the Dark Souls trilogy with faster combat and refined mechanics.",
                            Name = "Dark Souls III",
                            RequiredConnectorVersion = "3.2.0"
                        },
                        new
                        {
                            Id = 6,
                            ConnectorSupported = true,
                            Description = "Shinobi action game focused on sword combat and posture-based mechanics.",
                            Name = "Sekiro: Shadows Die Twice",
                            RequiredConnectorVersion = "3.2.0"
                        },
                        new
                        {
                            Id = 9,
                            ConnectorSupported = true,
                            Description = "Open-world action RPG with a vast world co-created with George R.R. Martin. Read live from the running game process via SoulMemory.",
                            Name = "Elden Ring",
                            RequiredConnectorVersion = "3.3.0"
                        });
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Legal.Entities.LegalDocument", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Kind");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Media.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Theme.Entities.SiteTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BackgroundAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("BackgroundTreatment")
                        .HasColumnType("integer");

                    b.Property<string>("DarkAccent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkDanger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkDefault")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkHighlight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkSuccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Font")
                        .HasColumnType("integer");

                    b.Property<string>("LightAccent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightDanger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightDefault")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightHighlight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightSuccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundAssetId");

                    b.ToTable("SiteThemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundTreatment = 3,
                            DarkAccent = "#c4b5fd",
                            DarkDanger = "#f87171",
                            DarkDefault = "#1e1e1e",
                            DarkHighlight = "#fbbf24",
                            DarkInfo = "#38bdf8",
                            DarkSuccess = "#4ade80",
                            Font = 0,
                            LightAccent = "#6d28d9",
                            LightDanger = "#b91c1c",
                            LightDefault = "#f5f5f5",
                            LightHighlight = "#b45309",
                            LightInfo = "#0369a1",
                            LightSuccess = "#15803d",
                            UpdatedAt = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Audits.Entities.AuditLog", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");

                    b.Navigation("Event");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.AllowlistedTwitchLogin", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.ApiKey", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Calendar.Entities.CalendarEntry", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Media.Entities.MediaAsset", "ImageAsset")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Event");

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Calendar.Entities.PlannedRun", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.EventGame", "EventGame")
                        .WithMany()
                        .HasForeignKey("EventGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.CompletedObjective", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Objective", "Objective")
                        .WithMany("CompletedObjectives")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.TrialRun", "TrialRun")
                        .WithMany("CompletedObjectives")
                        .HasForeignKey("TrialRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("TrialRun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Event", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventCompetitor", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany("Competitors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventCompetitorModerator", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.EventCompetitor", "Competitor")
                        .WithMany("Moderators")
                        .HasForeignKey("EventId", "CompetitorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventGame", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany("EventGames")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Games.Entities.Game", "KnownGame")
                        .WithMany()
                        .HasForeignKey("KnownGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("KnownGame");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventGameCompetitorInfo", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.EventGame", "EventGame")
                        .WithMany("CompetitorInfos")
                        .HasForeignKey("EventGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("EventGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventOverlayToken", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventRules", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithOne()
                        .HasForeignKey("Soulsjwa.Api.Features.Events.Entities.EventRules", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.FailedObjective", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Objective", "Objective")
                        .WithMany("FailedObjectives")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.TrialRun", "TrialRun")
                        .WithMany("FailedObjectives")
                        .HasForeignKey("TrialRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("TrialRun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Objective", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.EventGame", "EventGame")
                        .WithMany("Objectives")
                        .HasForeignKey("EventGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Soulsjwa.Api.Features.Games.Entities.Game", "Game")
                        .WithMany("PredefinedObjectives")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EventGame");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.TrialRun", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.EventGame", "EventGame")
                        .WithMany()
                        .HasForeignKey("EventGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Events.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Media.Entities.MediaAsset", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Theme.Entities.SiteTheme", b =>
                {
                    b.HasOne("Soulsjwa.Api.Features.Media.Entities.MediaAsset", "BackgroundAsset")
                        .WithMany()
                        .HasForeignKey("BackgroundAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BackgroundAsset");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Auth.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Event", b =>
                {
                    b.Navigation("Competitors");

                    b.Navigation("EventGames");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventCompetitor", b =>
                {
                    b.Navigation("Moderators");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.EventGame", b =>
                {
                    b.Navigation("CompetitorInfos");

                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.Objective", b =>
                {
                    b.Navigation("CompletedObjectives");

                    b.Navigation("FailedObjectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Events.Entities.TrialRun", b =>
                {
                    b.Navigation("CompletedObjectives");

                    b.Navigation("FailedObjectives");
                });

            modelBuilder.Entity("Soulsjwa.Api.Features.Games.Entities.Game", b =>
                {
                    b.Navigation("PredefinedObjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
