// <auto-generated />
// Source: SoulMemory NuGet (GPL-3, FrankvdStam/SoulSplitter).
// Game: DS3. Regenerate via tools/generate_soulmemory_boss_data.py.
namespace Soulsjwa.Api.Features.Games.Definitions;

/// <summary>
/// Boss table for DS3, extracted from SoulMemory's
/// <c>SoulMemory.DarkSouls3.Boss</c> enum. Each entry maps a SoulMemory id to a display
/// name, its in-game location, and a "main boss" flag (used by
/// predefined-objective scoring).
/// </summary>
public static class DarkSouls3BossData
{
    public sealed record Entry(long Id, string Name, string Category, bool IsMainBoss);

    public static readonly IReadOnlyList<Entry> All = new Entry[]
    {
        new(14000800, "Iudex Gundyr", "Cemetery of Ash", true),
        new(13000800, "Vordt Of The Boreal Valley", "High Wall of Lothric", false),
        new(13100800, "Curse Rotted Greatwood", "Undead Settlement", false),
        new(13300850, "Crystal Sage", "Road of Sacrifices", false),
        new(13300800, "Abyss Watchers", "Farron Keep", false),
        new(13500800, "Deacons Of The Deep", "Cathedral of the Deep", false),
        new(13800800, "High Lord Wolnir", "Catacombs of Carthus", false),
        new(13800830, "Old Demon King", "Smouldering Lake", false),
        new(13700850, "Pontiff Sulyvahn", "Irithyll of the Boreal Valley", true),
        new(13900800, "Yhorm The Giant", "Profaned Capital", false),
        new(13700800, "Aldrich Devourer Of Gods", "Anor Londo", true),
        new(13000890, "Dancer Of The Boreal Valley", "Lothric Castle", false),
        new(13010800, "Dragonslayer Armour", "Lothric Castle", false),
        new(13000830, "Oceiros The Consumed King", "Consumed King's Garden", false),
        new(14000830, "Champion Gundyr", "Untended Graves", false),
        new(13410830, "Lothric Younger Prince", "Grand Archives", false),
        new(13200800, "Ancient Wyvern", "Archdragon Peak", false),
        new(13200850, "Nameless King", "Archdragon Peak", true),
        new(14100800, "Soul Of Cinder", "Kiln of the First Flame", true),
        new(14500800, "Sister Friede", "Ariandel Chapel", true),
        new(14500860, "Champions Gravetender And Gravetender Greatwolf", "Ariandel Chapel", false),
        new(15000800, "Demon In Pain And Demon From Below Demon Prince", "Dreg Heap", false),
        new(15100800, "Halflight Spear Of The Church", "The Ringed City", false),
        new(15100850, "Darkeater Midir", "The Ringed City", true),
        new(15110800, "Slave Knight Gael", "Ringed City Streets", true),
    };
}
