// <auto-generated />
// Source: SoulMemory NuGet (GPL-3, FrankvdStam/SoulSplitter).
// Game: DS1R. Regenerate via tools/generate_soulmemory_boss_data.py.
namespace Soulsjwa.Api.Features.Games.Definitions;

/// <summary>
/// Boss table for DS1R, extracted from SoulMemory's
/// <c>SoulMemory.DarkSouls1.Boss</c> enum. Each entry maps a SoulMemory id to a display
/// name, its in-game location, and a "main boss" flag (used by
/// predefined-objective scoring).
/// </summary>
public static class DarkSouls1RemasteredBossData
{
    public sealed record Entry(long Id, string Name, string Category, bool IsMainBoss);

    public static readonly IReadOnlyList<Entry> All = new Entry[]
    {
        new(16, "Asylum Demon", "Northern Undead Asylum", false),
        new(3, "Bell Gargoyles", "Undead Parish", false),
        new(11010902, "Capra Demon", "Lower Undead Burg", false),
        new(11410900, "Ceaseless Discharge", "Demon Ruins", false),
        new(11410901, "Centipede Demon", "Demon Ruins", false),
        new(9, "Chaos Witch Quelaag", "Quelaag's Domain", false),
        new(4, "Crossbreed Priscilla", "Painted World of Ariamis", false),
        new(11510900, "Dark Sun Gwyndolin", "Anor Londo", false),
        new(11410410, "Demon Firesage", "Demon Ruins", false),
        new(13, "Four Kings", "New Londo Ruins", true),
        new(2, "Gaping Dragon", "The Depths", false),
        new(5, "Great Grey Wolf Sif", "Darkroot Garden", false),
        new(15, "Gwyn Lord Of Cinder", "Kiln of the First Flame", true),
        new(11, "Iron Golem", "Sen's Fortress", false),
        new(11200900, "Moonlight Butterfly", "Darkroot Garden", false),
        new(7, "Nito", "Tomb of the Giants", true),
        new(12, "Ornstein And Smough", "Anor Londo", true),
        new(6, "Pinwheel", "The Catacombs", false),
        new(14, "Seath The Scaleless", "Duke's Archives", true),
        new(11810900, "Stray Demon", "Firelink Shrine", false),
        new(11010901, "Taurus Demon", "Undead Burg", false),
        new(10, "Bed Of Chaos", "Lost Izalith", true),
        new(11210001, "Artorias The Abysswalker", "Royal Wood", true),
        new(11210004, "Black Dragon Kalameet", "Royal Wood", true),
        new(11210002, "Manus Father Of The Abyss", "Chasm of the Abyss", true),
        new(11210000, "Sanctuary Guardian", "Oolacile Sanctuary", false),
    };
}
