// <auto-generated />
// Source: SoulMemory NuGet (GPL-3, FrankvdStam/SoulSplitter).
// Game: DS2 SOTFS. Regenerate via tools/generate_soulmemory_boss_data.py.
namespace Soulsjwa.Api.Features.Games.Definitions;

/// <summary>
/// Boss table for DS2 SOTFS, extracted from SoulMemory's
/// <c>SoulMemory.DarkSouls2.BossType</c> enum. Each entry maps a SoulMemory id to a display
/// name, its in-game location, and a "main boss" flag (used by
/// predefined-objective scoring).
/// </summary>
public static class DarkSouls2ScholarBossData
{
    public sealed record Entry(long Id, string Name, string Category, bool IsMainBoss);

    public static readonly IReadOnlyList<Entry> All = new Entry[]
    {
        new(124, "The Last Giant", "Forest of Fallen Giants", true),
        new(112, "The Pursuer", "Forest of Fallen Giants", false),
        new(52, "Executioners Chariot", "Cave of the Dead", false),
        new(72, "Looking Glass Knight", "Drangleic Castle", false),
        new(56, "The Skeleton Lords", "Huntsman's Copse", false),
        new(84, "Flexile Sentry", "Lost Bastille", false),
        new(92, "Lost Sinner", "Lost Bastille", true),
        new(168, "Belfry Gargoyles", "Shaded Woods", false),
        new(88, "Ruin Sentinels", "Lost Bastille", false),
        new(100, "Royal Rat Vanguard", "The Gutter", false),
        new(108, "Royal Rat Authority", "Black Gulch", false),
        new(68, "Scorpioness Najka", "Harvest Valley", false),
        new(44, "The Dukes Dear Freja", "Brightstone Cove Tseldora", false),
        new(64, "Mytha The Baneful Queen", "Earthen Peak", false),
        new(104, "The Rotten", "Black Gulch", true),
        new(80, "Old Dragon Slayer", "Heide's Tower of Flame", false),
        new(60, "Covetous Demon", "Harvest Valley", false),
        new(96, "Smelter Demon", "Iron Keep", false),
        new(48, "Old Iron King", "Iron Keep", true),
        new(120, "Guardian Dragon", "Dragon Aerie", false),
        new(40, "Demon Of Song", "Brightstone Cove Tseldora", false),
        new(140, "Velstadt The Royal Aegis", "Drangleic Castle", false),
        new(152, "Vendrick", "Undead Crypt", true),
        new(156, "Darklurker", "Dark Chasm of Old", false),
        new(76, "Dragonrider", "Heide's Tower of Flame", false),
        new(160, "Twin Dragonriders", "Drangleic Castle", false),
        new(164, "Prowling Magnus And Congregation", "Brightstone Cove Tseldora", false),
        new(128, "Giant Lord", "Memory of the Giants", false),
        new(148, "Ancient Dragon", "Dragon Shrine", false),
        new(136, "Throne Watcher And Throne Defender", "Drangleic Castle", false),
        new(132, "Nashandra", "Drangleic Castle", true),
        new(280, "Aldia Scholar Of The First Sin", "Aldia's Keep", true),
        new(200, "Elana Squalid Queen", "Shulva, Sanctum City", false),
        new(212, "Sinh The Slumbering Dragon", "Dragon's Rest", false),
        new(244, "Afflicted Graverobber Ancient Soldier Varg Cerah The Old Explorer", "Brume Tower", false),
        new(252, "Blue Smelter Demon", "Brume Tower", false),
        new(204, "Fumeknight", "Brume Tower", true),
        new(248, "Sir Alonne", "Iron Passage", true),
        new(260, "Burnt Ivory King", "Frozen Eleum Loyce", true),
        new(208, "Aava The Kings Pet", "Frigid Outskirts", false),
        new(264, "Lud And Zallen The Kings Pets", "Frozen Eleum Loyce", false),
    };
}
