// <auto-generated />
// Source: SoulMemory NuGet (GPL-3, FrankvdStam/SoulSplitter).
// Game: Sekiro. Regenerate via tools/generate_soulmemory_boss_data.py.
namespace Soulsjwa.Api.Features.Games.Definitions;

/// <summary>
/// Boss table for Sekiro, extracted from SoulMemory's
/// <c>SoulMemory.Sekiro.Boss</c> enum. Each entry maps a SoulMemory id to a display
/// name, its in-game location, and a "main boss" flag (used by
/// predefined-objective scoring).
/// </summary>
public static class SekiroBossData
{
    public sealed record Entry(long Id, string Name, string Category, bool IsMainBoss);

    public static readonly IReadOnlyList<Entry> All = new Entry[]
    {
        new(9301, "Gyoubu Masataka Oniwa", "Ashina Castle", false),
        new(9302, "Lady Butterfly", "Hirata Estate", false),
        new(9303, "Genichiro Ashina", "Ashina Castle", true),
        new(9305, "Folding Screen Monkeys", "Senpou Temple, Mt. Kongo", false),
        new(9304, "Guardian Ape", "Sunken Valley", false),
        new(9307, "Headless Ape", "Bodhisattva Valley", false),
        new(9306, "Corrupted Monk Ghost", "Ashina Depths", false),
        new(9315, "Emma The Gentle Blade", "Ashina Castle", true),
        new(9316, "Isshin Ashina", "Ashina Castle", false),
        new(9308, "Great Shinobi Owl", "Ashina Castle", true),
        new(9309, "True Corrupted Monk", "Fountainhead Palace", true),
        new(9310, "Divine Dragon", "Divine Realm of the Dragon's Homeland", true),
        new(9317, "Owl Father", "Ashina Castle", true),
        new(9313, "Demon Of Hatred", "Ashina Outskirts", true),
        new(9312, "Isshin The Sword Saint", "Ashina Castle", true),
    };
}
